# Generated by Django 2.2 on 2020-07-06 20:49

import accounts.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible_name', models.CharField(max_length=50)),
                ('user_own_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('private_user_id', models.CharField(db_index=True, default=accounts.utils.get_private_user_id, max_length=16, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
